import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// components
import { Footer } from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Demo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex w-screen min-h-screen flex-col items-center justify-start overflow-x-hidden'>
          {children}
          {/* footer 因为使用了fixed 定位，会不受父容器宽度限制，不放在 children 里 */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
